"""The document QA workshop runs in a uv isolated environment: no kernel install, no restart, hashed wheels.

Static checks of the notebook, the carried stage file and the lock, plus stage-CLI runs on stand-in state
(no models, no network). Not execution evidence for a hosted runtime.
"""

import ast
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import build_document_qa_workshop_carrier as carrier
import document_qa_workshop as dqa
import pytest

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "tutorials" / "DIMER_Document_QA_LayoutLM_vs_Pix2Struct_Workshop.ipynb"
STAGE_FILE = ROOT / "tools" / "document_qa_workshop.py"
LOCK = ROOT / "tools" / "document-qa-workshop-requirements.lock"
REQUIREMENTS = ROOT / "tools" / "document-qa-workshop-requirements.in"
FORMER_PINS = {
    "torch": "2.14.0", "torchvision": "0.29.0", "torchaudio": "2.11.0", "transformers": "4.57.6",
    "safetensors": "0.8.0", "numpy": "2.5.3", "pillow": "11.3.0", "huggingface-hub": "0.36.2",
    "pyarrow": "25.0.1",
}
# The kernel may import only the standard library and what hosted runtimes ship, for display.
KERNEL_IMPORTS = {"ast", "hashlib", "io", "json", "os", "platform", "subprocess", "sys", "time", "urllib",
                  "zipfile", "pathlib", "IPython", "numpy", "pandas", "matplotlib", "PIL"}


def _notebook():
    return json.loads(NOTEBOOK.read_text(encoding="utf-8"))


def _code_cells():
    return [(c["id"], "".join(c["source"])) for c in _notebook()["cells"] if c["cell_type"] == "code"]


def _src(cid):
    return next(s for i, s in _code_cells() if i == cid)


def test_no_kernel_install_or_restart_guard():
    for cid, source in _code_cells():
        if cid == "uvcarrier":
            continue
        assert not re.search(r"-m\W+pip|^\s*[%!]\s*pip", source, re.M), cid
        for install in re.findall(r'"pip", "install"[^\n]*', source):
            assert '"--python", str(PYTHON)' in install, (cid, install)  # into the venv only
        for banned in ("Restart session", "NUMPY_PRELOADED", "sys.executable", "importlib.metadata"):
            assert banned not in source, (cid, banned)
    markdown = "\n".join("".join(c["source"]) for c in _notebook()["cells"] if c["cell_type"] == "markdown")
    assert "no restart" in markdown.lower() and "Linux x86_64 only" in markdown


def test_kernel_imports_only_the_standard_library_and_hosted_display_packages():
    for cid, source in _code_cells():
        for node in ast.walk(ast.parse(source)):
            if isinstance(node, ast.Import):
                names = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            for name in names:
                assert name.split(".")[0] in KERNEL_IMPORTS, (cid, name)


def test_lock_has_hashes_for_every_requirement_and_keeps_the_former_pins():
    text = LOCK.read_text(encoding="utf-8")
    hashed = r"((?:    --hash=sha256:[0-9a-f]{64}(?: \\)?\n)+)"
    blocks = re.findall(r"^([A-Za-z0-9_.-]+)==(\S+) \\\n" + hashed, text, re.M)
    pinned = {name.lower(): version for name, version, _ in blocks}
    requirement_lines = [ln for ln in text.splitlines() if re.match(r"^[A-Za-z0-9_.-]+==", ln)]
    assert len(blocks) == len(requirement_lines) >= 40
    for name, version in FORMER_PINS.items():
        assert pinned[name] == version, name
        assert f"{name} {version}" in text.split("# This file was autogenerated")[0], name
    direct = dict(ln.split("==") for ln in REQUIREMENTS.read_text(encoding="utf-8").splitlines()
                  if ln and not ln.startswith("#"))
    assert direct == FORMER_PINS
    assert "--python-platform x86_64-manylinux_2_28" in text and "--only-binary :all:" in text


def test_runtime_cell_pins_uv_and_installs_with_require_hashes_only_binary():
    source = _src("7984f79d")
    assert '"--require-hashes", "--only-binary", ":all:"' in source
    assert "uv-0.12.15-py3-none-manylinux_2_17_x86_64" in source
    assert 'UV_SHA256 = "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60"' in source
    assert '"venv", "--clear", "--managed-python", "--python", "3.12.12"' in source
    assert 'platform.system() != "Linux" or platform.machine() != "x86_64"' in source
    assert 'ENV["MPLBACKEND"] = "Agg"' in source
    assert '("HF_TOKEN", "HUGGING_FACE_HUB_TOKEN", "PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP")' in source


def test_stages_run_with_the_venv_python():
    source = _src("7984f79d")
    assert 'PYTHON = ENV_ROOT / "bin" / "python"' in source
    assert 'command = [str(PYTHON), "-u", str(STAGE_SCRIPT), "--config"' in source
    assert 'STAGE_SCRIPT = RUNNER_ROOT / "document_qa_workshop.py"' in source
    called = set()
    for _, cell in _code_cells():
        called.update(re.findall(r'run_stage\(\s*"([a-z0-9-]+)"', cell))
    assert called == set(dqa.STAGES)


def test_no_cell_line_is_longer_than_2000_characters():
    for cell in _notebook()["cells"]:
        for line in "".join(cell["source"]).splitlines():
            assert len(line) <= 2000, (cell["id"], len(line))


def test_carrier_cell_matches_the_tools_files():
    assert carrier.main(["--check"]) == 0
    carried = _notebook()["metadata"]["dimer"]["carried_files"]
    assert carried["document_qa_workshop.py"]["sha256"] == hashlib.sha256(STAGE_FILE.read_bytes()).hexdigest()
    assert carried["requirements.lock.txt"]["sha256"] == hashlib.sha256(LOCK.read_bytes()).hexdigest()
    order = [c["id"] for c in _notebook()["cells"]]
    assert order.index("5f810ac8") < order.index("uvcarrier") < order.index("7984f79d")


def test_carrier_cell_writes_files_that_hash_to_the_lock(tmp_path):
    ns = {"WORK_DIR": str(tmp_path / "work")}
    exec(compile(_src("uvcarrier"), "uvcarrier", "exec"), ns)
    runner = tmp_path / "work" / "runner"
    assert (runner / "document_qa_workshop.py").read_bytes() == STAGE_FILE.read_bytes()
    assert (runner / "requirements.lock.txt").read_bytes() == LOCK.read_bytes()


def test_uv_revision_is_logged_in_the_notebook_metadata():
    revisions = _notebook()["metadata"]["dimer"]["review_revisions"]
    entry = next(r for r in revisions if r["date"] == "2026-10-03")
    assert entry["change"] == "uv isolated environment" and entry["hosted_execution"] == "pending"


def test_docs_say_linux_x86_64_only():
    row = next(ln for ln in (ROOT / "tutorials" / "README.md").read_text(encoding="utf-8").splitlines()
               if "DIMER_Document_QA_LayoutLM_vs_Pix2Struct_Workshop.ipynb" in ln and ln.startswith("|"))
    assert "Linux x86_64 only" in row and "| Candidate" in row.replace("**", "")
    verification = (ROOT / "docs" / "release-verification.md").read_text(encoding="utf-8")
    assert "2026-10-03 uv isolated environment" in verification


# ---- stage CLI on stand-in state ----------------------------------------------------------------------
def _row(model, record, answer, **extra):
    gold = record["answers"]
    return {
        "record_id": record["id"], "page_id": record["page_id"], "field": record["field"],
        "question": record["question"], "gold_answer": gold[0], "model": model, "answer": answer,
        "normalized_answer": dqa.normalize_answer(answer), "anls": dqa.anls(answer, gold),
        "exact_match": dqa.exact_match(answer, gold), "empty": not answer.strip(),
        "answer_in_ocr": dqa.answer_in_ocr(answer, record["words"]), "latency_seconds": 0.01, **extra,
    }


def _standin_state(work):
    words = ["TOTAL", "3.30", "TAX", "0.30"]
    boxes = [[0, 0, 10, 10], [20, 0, 30, 10], [0, 20, 10, 30], [20, 20, 30, 30]]
    records = [
        {"id": f"test-{k:04d}", "page_id": f"test-{k // 2:03d}", "field": field, "question": question,
         "words": words, "boxes": boxes, "image_size": [40, 40], "answers": [gold],
         "answer_start": 1, "answer_end": 1}
        for k, (field, question, gold) in enumerate([
            ("total.total_price", "What is the total amount?", "3.30"),
            ("sub_total.tax_price", "What is the tax amount?", "0.30"),
        ] * 2)
    ]
    pages = [{"id": f"test-{k:03d}", "words": words, "boxes": boxes, "image_size": [40, 40], "lines": [],
              "source_split": "test", "source_row": k, "pixel_sha256": "0" * 64, "ocr_sha256": "1" * 64}
             for k in range(2)]
    lrows = [_row("LayoutLM", r, "3.30", start_word=1, end_word=1, span_score=0.9, n_windows=1,
                  answer_union_box=[20, 0, 30, 10], new_tokens=None, truncated=None) for r in records]
    prows = [_row("Pix2Struct", r, "3.3", start_word=None, end_word=None, span_score=None, n_windows=None,
                  answer_union_box=None, new_tokens=3, truncated=False) for r in records]
    probe = {"check": "x", "refused": True, "message": "m"}
    state = {
        "environment.json": {"python": "3.12.12", "device": "cpu"},
        "dataset.json": {"supported_unique_pages": 2, "page_splits": {"test": 2}, "qa_splits": {"test": 4},
                         "test_qa_digest": "d" * 64, "test_records": records, "test_pages": pages},
        "baselines.json": {"last_number_rows": [_row("Last-number baseline", r, "0.30") for r in records],
                           "keyword_rows": [_row("Keyword lookup", r, "3.30") for r in records]},
        "layoutlm_check.json": {"parameter_count": 127_792_898, "load_seconds": 1.0,
                                "rejection_probes": [probe] * 3},
        "pix2struct_check.json": {"parameter_count": 282_285_696, "load_seconds": 2.0,
                                  "font_sha256": "f" * 64, "rejection_probes": [probe] * 3},
        "layoutlm_eval.json": {"rows": lrows, "times": [0.01] * 4, "peak_gpu_memory_bytes": None},
        "pix2struct_eval.json": {"rows": prows, "times": [0.5] * 4, "peak_gpu_memory_bytes": None},
        "layoutlm_no_layout.json": {"rows": []},
        "pix2struct_degraded.json": {"rows": []},
        "layoutlm_probes.json": {"paraphrase_rows": [], "unanswerable_rows": []},
        "pix2struct_probes.json": {"paraphrase_rows": [], "unanswerable_rows": []},
    }
    (work / "state").mkdir(parents=True)
    for name, value in state.items():
        (work / "state" / name).write_text(json.dumps(value), encoding="utf-8")


def _config(tmp_path, **overrides):
    config = {
        "use_byod": False, "byod_path": "", "max_new_tokens": 32, "run_paraphrase_experiment": True,
        "paraphrase_max_records": 20, "run_unanswerable_probe": True, "unanswerable_pages": 5,
        "run_modality_robustness": True, "robustness_max_records": 20,
        "output_dir": str(tmp_path / "out"), "work_dir": str(tmp_path / "work"),
    }
    config.update(overrides)
    path = tmp_path / "stage_config.json"
    path.write_text(json.dumps(config), encoding="utf-8")
    return path


def _stage(config, stage, *options):
    command = [sys.executable, str(STAGE_FILE), "--config", str(config), "--stage", stage, *options]
    return subprocess.run(command, capture_output=True, text=True, encoding="utf-8", timeout=120)


@pytest.mark.parametrize("stage", ["compare", "fields", "agreement", "off-page", "paraphrase", "unanswerable",
                                   "windows", "resources"])
def test_display_stages_run_from_state_without_models(tmp_path, stage):
    _standin_state(tmp_path / "work")
    done = _stage(_config(tmp_path), stage)
    assert done.returncode == 0, done.stdout + done.stderr
    assert "torch" not in done.stderr
    if stage == "compare":
        assert "LayoutLM" in done.stdout and "1.000" in done.stdout


def test_export_and_summary_stages_write_every_required_output(tmp_path):
    _standin_state(tmp_path / "work")
    config = _config(tmp_path)
    assert _stage(config, "export").returncode == 0
    for name in dqa.REQUIRED_OUTPUTS:
        assert (tmp_path / "out" / name).is_file(), name
    manifest = json.loads((tmp_path / "out" / "input_manifest.json").read_text(encoding="utf-8"))
    assert len(manifest["rejection_probes"]) == 6
    summary = _stage(config, "summary")
    assert summary.returncode == 0 and re.search(r"^LayoutLM\s+\d\.\d{3}\s+\d\.\d{3}", summary.stdout, re.M)


def test_a_refusal_exits_2_with_the_message_for_the_notebook(tmp_path):
    done = _stage(_config(tmp_path, use_byod=True, byod_path=""), "byod")
    assert done.returncode == dqa.REFUSAL_EXIT
    assert "BYOD_PATH is empty" in (tmp_path / "work" / "state" / "refusal.txt").read_text(encoding="utf-8")


def test_an_out_of_range_control_is_refused_by_the_stage(tmp_path):
    done = _stage(_config(tmp_path, robustness_max_records=0), "compare")
    assert done.returncode == dqa.REFUSAL_EXIT and "ROBUSTNESS_MAX_RECORDS" in done.stdout
