"""DIMER inference package for the pinned ``impira/layoutlm-document-qa`` checkpoint."""

from .pipeline import (
    ANLS_THRESHOLD,
    BOX_GRID,
    DEFAULT_WEIGHTS_DIR,
    DOC_STRIDE,
    INPUT_SCHEMA,
    MAX_ANSWER_TOKENS,
    MAX_IMAGE_SIDE,
    MAX_QUESTION_CHARS,
    MAX_SEQ_LEN,
    MAX_WORDS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    LayoutLMDocumentQAPipeline,
    anls,
    evaluation_report,
    exact_match,
    normalize_answer,
    normalize_box,
    ocr_words_with_tesseract,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "ANLS_THRESHOLD",
    "BOX_GRID",
    "DEFAULT_WEIGHTS_DIR",
    "DOC_STRIDE",
    "INPUT_SCHEMA",
    "MAX_ANSWER_TOKENS",
    "MAX_IMAGE_SIDE",
    "MAX_QUESTION_CHARS",
    "MAX_SEQ_LEN",
    "MAX_WORDS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "LayoutLMDocumentQAPipeline",
    "anls",
    "evaluation_report",
    "exact_match",
    "normalize_answer",
    "normalize_box",
    "ocr_words_with_tesseract",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
