"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, metrics.py, samples.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures an E2E document-QA workflow: the pinned impira/layoutlm-document-qa snapshot
is digest-verified and loaded, the `ground_truth` column of two digest-pinned CORD-v2 receipt shards is
fetched, turned into templated question/answer records over real OCR words and boxes, validated and
split by page, five authored questions over a rendered invoice are answered through the inference
contract, the frozen model is scored on the held-out receipts beside two non-neural baselines, a
bounded fine-tuning of the last encoder blocks and the span head runs, the held-out split is scored
again, the adapted model re-reads the invoice, the adapter is exported and reloaded, and questions the
page cannot answer are put to both models.

Review fixes (Notebook Review Framework v1, review PR #13, LDQ-M1..M3 / LDQ-m1..m5): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); Sections 5-7 start from the pretrained model on every
re-run and `adapt` refuses an adapted pipeline, so a documented experiment or a BYOD re-run never reads the adapted
model as "frozen" and the exported adapter always reproduces the evaluated model; BYOD states and checks its real
minimum (12 records with one question per page), names the split it refuses, reports the JSONL line of a parse
error and takes a path (`BYOD_PATH`) as well as a Colab upload; the schema renders with single braces; the expected
validation ANLS quotes the recorded run with its environment and the per-field regression is stated; the results
are recorded, not asserted; and the guided layer (audience, task contract, how to use, roadmap, predictions, worked
answers, a runnable unsupported-question probe, a change-one-thing activity, troubleshooting, glossary, conclusion)
is added with the setup cells labelled Infrastructure and collapsed.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "layoutlm_document_qa_pipeline",
    "repo_name": "layoutlm-document-qa-pipeline",
    "stem": "layoutlm_document_qa",
    "notebook_name": "layoutlm_document_qa_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "collapse_model_cell": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline;
    # generator /2.1 as in florence2-vision-language-pipeline 9c4e95a): managed CPython, a size- and SHA-256-verified uv
    # wheel, and a hash lock of the pyproject pins. The pins are identical to florence2-vision-language-pipeline's, and
    # tutorials/requirements-colab.lock.txt is that repository's lock byte for byte (Colab T4 PASS at 9c4e95a); its 48
    # versions and hashes are also exactly those of this repository's own workshop lock
    # (tools/document-qa-workshop-requirements.lock, Colab CLI T4 PASS at cf98b6e).
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned `impira/layoutlm-document-qa` snapshot (safetensors, 511 MB), reads the `ground_truth` column of two "
        "digest-pinned CORD-v2 receipt shards from the Hugging Face Hub (about 0.4 MB over HTTP range requests, no credential), "
        "turns the 199 unique receipts into templated question/answer records over their real OCR words and boxes and cuts "
        "them by receipt into 119 / 30 / 50 training, validation and test pages, drops any record that would not fit one "
        "512-token window, answers five authored questions over a rendered invoice through the inference contract with an "
        "input manifest and a rejection probe, scores the frozen model on the test receipts with ANLS and exact match beside "
        "the last-number and keyword-lookup baselines, runs a bounded fine-tuning of the last four encoder blocks and the span "
        "head on the training receipts with validation-ANLS epoch selection, scores the held-out receipts again, re-reads the "
        "invoice with the adapted model, exports the adapter as safetensors with a manifest, reloads that artifact into a "
        "fresh pipeline to verify answer parity, and puts three questions the invoice cannot answer to both models. The "
        "default path needs no repository clone, no DIMER worker or service, no credential, no upload dialog and no "
        "configuration edit (NOTEBOOK_SPEC 2.2 §5). On CPU the model stages take about twenty minutes after the downloads; a "
        "CUDA runtime is used automatically when present (the six epochs took 82 s on a Kaggle Tesla T4). Building the "
        "isolated environment comes on top of this."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over into a *frozen* number or into your adapter). Supply one JSON array or "
        "JSONL file of `{id, page_id, question, words, boxes, image_size, answer_start, answer_end}` records — the page's "
        "OCR words with one pixel `[x0, y0, x1, y1]` box each, the page size, and the inclusive word indices of the gold "
        "span — through the upload dialog on Colab, or as a path in `BYOD_PATH` on any runtime. It needs **at least 12 "
        "records with one question per page**: the seeded split keeps 20 % for test and 15 % for validation and must leave "
        "at least 8 training, 2 validation and 2 test records, and a page with several questions moves as a whole, so such "
        "a dataset can need more; Section 4 checks this before any model runs and names the split it refuses, and a file "
        "that is not valid JSON is refused with its line number. The records pass through the same validation, seeded "
        "page-disjoint split, fit check, baselines, fine-tuning, held-out evaluation, artifact export and reload-parity "
        "cells as the CORD-v2 sample; a result where the adapted model does not beat the frozen one is reported, not "
        "treated as an error. Uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "LayoutLMDocumentQAPipeline",
    "weights_key": "layoutlm-document-qa",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "transformers"],
    "title": "LayoutLM Document QA (impira) — DIMER E2E document question-answering fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/layoutlm-document-qa-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/layoutlm-document-qa-pipeline/blob/main/tutorials/layoutlm_document_qa_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-impira%2Flayoutlm--document--qa-ffcc4d?style=flat",
            "https://huggingface.co/impira/layoutlm-document-qa",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-microsoft%2Funilm%20(layoutlm)-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/microsoft/unilm/tree/master/layoutlm",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-1912.13318-b31b1b.svg", "https://arxiv.org/abs/1912.13318"),
    ],
    "capability": "extractive document question answering over OCR words and boxes and bounded supervised fine-tuning of the last encoder blocks and the span head on a gold-span receipt dataset, using the pinned `impira/layoutlm-document-qa` weights",
    "intro": (
        "`impira/layoutlm-document-qa` is Impira's LayoutLM (v1) — a 12-layer BERT-style encoder with 2-D position "
        "embeddings, 128 M parameters, RoBERTa vocabulary — fine-tuned on SQuAD 2.0 and DocVQA for extractive document "
        "question answering and published under the **MIT** licence. At inference the encoder reads the question and the "
        "page's **words with their boxes** (normalised to a 0–1000 grid) as one token sequence and emits a start and an end "
        "logit per token; the carried module scores every span of at most 15 tokens by the product of the start and end "
        "softmax probabilities and returns the best one as a word span with its indices. **The model never sees pixels:** "
        "OCR is an input provider outside the model, so words and boxes come from the caller (bring-your-own OCR), and the "
        "model has no abstention — it returns its best span for every question.\n\n"
        "What this notebook adds to inference is **adaptation with gold spans**. The dataset is real: CORD-v2 (Park et al., "
        "2019; NAVER Clova; **CC BY 4.0**) — photographed Indonesian receipts whose every printed word carries a pixel box and "
        "a field category. Because the model needs words and boxes only, the notebook reads just the `ground_truth` column of "
        "two pinned Hub parquet shards (about 0.4 MB of the 476 MB the shards hold with their images) and turns each receipt "
        "into templated questions — *What is the total amount?*, *How much change was given?*, *What is the name of the first "
        "item?* — whose gold answer is the value words of the matching field, a contiguous span of the page's OCR words by "
        "construction. The frozen model already reads most receipt totals (ANLS 0.843 on the test receipts in the recorded "
        "Kaggle Tesla T4 run), so the fine-tuning question is narrower and more honest than a rescue: does a bounded "
        "adaptation of the last four encoder blocks and the span head on 119 receipts lift the fields it gets wrong — item "
        "names, quantities, cash and change lines — on held-out receipts, and does any field get worse? Two metrics are "
        "implemented in the carried modules (mean **ANLS**, DocVQA's official normalised-Levenshtein score, and the "
        "**exact-match** rate after the same normalisation), and two **non-neural baselines** — last number on the page and "
        "keyword lookup — show where a reader with no model sits. Nothing here is a quality claim about your documents: it "
        "is one seeded split of one corpus with one OCR convention.\n\n"
        "**Snapshot note:** the pinned revision ships a fast `tokenizer.json` (an 8-file manifest) and a float32 "
        "`model.safetensors` — no pickle is opened anywhere in this notebook; the upstream `pytorch_model.bin` and "
        "`tf_model.h5` are neither listed nor fetched. Section 3 stages and digest-verifies those eight files before the "
        "tokenizer or the model is constructed.\n\n"
        "**Who this is for.** A learner who knows basic Python and PIL, has met the idea of a pretrained model, and wants to "
        "see how a document question-answering model is measured against gold answers and adapted to one document family. "
        "No prior experience with LayoutLM, span extraction, ANLS or fine-tuning is assumed; each term is explained where it "
        "is first used and again in the **Glossary** at the end. A CPU runtime is enough (Prerequisites).\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Inference | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | one question (at most 256 characters) and one page's OCR words (1 to 2,000) with one pixel box each and the page size | 595 templated questions over 119 receipts, each with the page's words and boxes and the word indices of the gold answer |\n"
        "| Model | LayoutLM v1: words + 2-D boxes → 12 encoder blocks → a start and an end logit per token; the best span of at most 15 tokens | the same model with the last four encoder blocks and the span head trained (28.4 M of 127.8 M parameters), everything else frozen |\n"
        "| Output | a word span (`answer`, `start`, `end`) and a span `score` — a ranking signal, not a probability | an adapter (safetensors) and held-out ANLS / exact match per field beside two baselines and the frozen model |\n\n"
        "**How to use this notebook.** Choose a runtime, then **Runtime → Run all**. Sections 1–3 are **infrastructure** — "
        "the isolated environment, the carried code and the model verification — and can be run without study; their code is "
        "collapsed. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant to be edited; "
        "the defaults reproduce the recorded path. Each stage asks you to **predict** before it runs, and the next cell opens "
        "with **What to notice** and a collapsible **Check your reasoning** block with a worked answer from the recorded "
        "Kaggle Tesla T4 run of the previous notebook version (same model stages; a CPU or another GPU gives the same frozen "
        "numbers and training results within about 0.01 — see **Run-to-run spread** in Section 7). Section 10 is a short "
        "probe you can edit, Section 11 a **change-one-thing activity**, and each optional experiment names the cell to "
        "change and the cells to re-run. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. "
        "Your notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the receipts → 5 answer questions on a rendered invoice with the "
        "pretrained model → 6 two baselines and the pretrained model on the test receipts → 7 fine-tune the last four "
        "blocks → 8 compare on the held-out receipts, field by field → 9 re-read the invoice, export and reload → 10 ask "
        "questions the page cannot answer → 11 **change one thing: two trainable blocks** → conclude. Core concepts are "
        "Sections 5, 6 and 10 (what the model returns and how it is scored); evaluation practice is Sections 4, 7 and 8 "
        "(split, selection, held-out comparison); engineering and reproducibility are Sections 1–3 and 9."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *question + OCR words and boxes → start/end logits → best word span* "
        "and say why the span `score` is not a calibrated probability (Sections 5 and 10); (2) read ANLS and exact match "
        "against a last-number and a keyword-lookup baseline and say what each baseline rules out (Section 6); (3) explain "
        "why every question on one page stays in one split and how the validation split, never the test split, chooses the "
        "kept epoch (Sections 4 and 7); (4) predict and then check how each field moves after a bounded fine-tuning, "
        "including a field that gets worse, and say which per-field numbers are too small to read (Section 8); (5) check "
        "that an exported adapter reproduces the evaluated model (reload parity, Section 9); (6) show that the model "
        "returns a span even when the page cannot answer the question (Section 10); and (7) predict and then observe what "
        "training two blocks instead of four changes (Section 11)."
    ),
    "exclusions": (
        "OCR itself (the notebook installs no Tesseract and ships no OCR model; the default path uses the corpus's annotated "
        "words and boxes and the invoice renderer's own boxes), PDF or multi-page documents (one page per call), abstention "
        "(the model always returns its best span, even for an unanswerable question), answers that are not a contiguous span "
        "of the OCR words, arithmetic or reasoning, evaluation on the DocVQA benchmark (registration-gated and not bundled), "
        "full-model or embedding fine-tuning, training on pages that need more than one window, languages and scripts other "
        "than the Latin-script receipts and English questions used here, and any claim that a CORD-v2 split stands in for your "
        "documents. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and PIL, and Colab or Jupyter familiarity. No prior experience with LayoutLM, span extraction, ANLS or fine-tuning: the notebook explains span scores, ANLS and exact match, the two baselines, the fit check and validation-based epoch selection where they are first used, and the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own **Python 3.12.12** environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter (Colab's kernel runs Python 3.13 as of September 2026; the stages still run on 3.12.12), and a Windows or macOS kernel is not supported (Section 1 stops with that message). The default path runs on CPU (float32) and uses CUDA automatically when present. CPU is adequate but not fast: a CPU pre-flight of the previous notebook version took about 7 s to load and digest-verify the 514 MB snapshot, 41 s to score the 229 test questions, and 934 s for the six epochs of fine-tuning with validation scoring; the recorded Kaggle Tesla T4 run took 82 s for the six epochs. The locked install (PyTorch 2.14.0 with its CUDA libraries, a few GB) and the 511 MB checkpoint are the large downloads of the run.",
        "- **Knowledge:** what extractive (span) question answering over OCR tokens is; why a start/end softmax product is not a calibrated confidence; what normalised Levenshtein similarity (ANLS) measures and why neither it nor exact match is a human judgement. Each is explained again where it is used.",
        "- **Data contract:** records are `{id, page_id, question, words, boxes, image_size, answer_start, answer_end}` — the page's OCR words (1..`MAX_WORDS` = 2,000, non-empty) with one pixel `[x0, y0, x1, y1]` box per word inside the page, the page size in pixels (`MIN_IMAGE_SIDE`..`MAX_IMAGE_SIDE` = 1..10,000), a question of at most `MAX_QUESTION_CHARS` (256) characters, and the inclusive word indices of the gold span; an optional `answers` list must start with the span text. Ids match `[A-Za-z0-9_.:-]{1,64}` and are unique; a training split needs 8..20,000 records and the validation and test splits at least 2 each, so **a BYOD dataset needs at least 12 records with one question per page** (Section 4 computes and prints this minimum, checks it before any model runs and names the split it refuses); every question on the same page lands in the same split so a test page is never trained on; a question + page that needs more than one 512-token window is dropped from training by the fit check, never truncated.",
        "- **BYOD layout:** one `.json` file holding an array of records, or one `.jsonl` file with one record object per line, by upload on Colab or by path in `BYOD_PATH` on any runtime. A line that is not valid JSON is refused with the file name and the line number.",
        "- **Validation is structural, not semantic:** nothing checks that a question is answerable from its page beyond the gold span lying inside the words, or that a gold span is the *best* answer — a mislabelled corpus is fine-tuned on without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — an internal document set with its field annotations is exactly that. The default path uploads nothing.",
        "- **External access (data):** besides the model snapshot, the default path reads the `ground_truth` column of two objects in the Hub dataset repository `naver-clova-ix/cord-v2` at the immutable revision `7f0115a4…` (`data/test-…parquet`, 234,202,795 bytes, SHA-256 `51c65f17…`, and `data/validation-…parquet`, 242,080,800 bytes, SHA-256 `0d0f6dac…`): the declared size and SHA-256 of each file are checked against the pins before any byte is read, only the parquet footer and that one column are fetched over HTTPS range requests, and the decoded column is refused unless its own SHA-256 matches; the corpus is CC BY 4.0 (Park et al., 2019). No image is downloaded.",
    ],
    "cells": [
        {
            "md": (
                "## 4. CORD-v2 receipt corpus, validation and split\n\n"
                "`fetch_corpus` reads the pinned shards' `ground_truth` column (or the cache under `weights/cord-v2/`): for "
                "each shard it first checks the byte size and SHA-256 the Hub declares for the file against the pins, then "
                "reads only the parquet footer and the one column chunk through `pyarrow` over HTTPS range requests, and "
                "refuses the decoded column unless its SHA-256 matches. `read_corpus` turns each row into a page — the words "
                "of every annotated line in order, each box the clipped axis-aligned hull of the annotated quadrilateral, and "
                "the lines' field categories with their value-word spans (`is_key` 0; a printed key such as `TOTAL` is on the "
                "line but not in the answer). `build_sample_dataset` keeps every receipt that supports at least one templated "
                "question, drops the one receipt whose words repeat another shard's, shuffles the 199 unique receipts with "
                "`SPLIT_SEED` and cuts them **by receipt** into 119 / 30 / 50 training, validation and test pages, then expands "
                "each page into its questions (a category that occurs on exactly one line becomes one question; *first item* "
                "is the topmost single-line `menu.nm`). `validate_dataset` checks every record against the contract (each split "
                "against its own minimum from `split_minimums()`), `check_split_disjoint` asserts no page id and no page "
                "content is shared, and the training split is written to `outputs/{stem}_train.jsonl` in the shape BYOD "
                "expects.\n\n"
                "**What the split does and does not protect against.** No receipt is in two splits, so the test score is never "
                "computed on a page the model trained on. But CORD-v2 records no shop or vendor, and many receipts come from "
                "the same few point-of-sale layouts, so receipts of one shop can sit in training and in test. The held-out "
                "scores in Section 8 are therefore an estimate for *more receipts like these*, not for another country's or "
                "another business's documents.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a `.json` / `.jsonl` file already in this runtime, then select this cell and choose "
                "**Runtime → Run after**. An empty or cancelled upload, a runtime without the Colab upload dialog and no "
                "`BYOD_PATH`, or a path that does not exist stops with a message saying what to supply. `load_byod_dataset` "
                "names the line of a malformed JSONL record, `validate_dataset` names the record and the rule it breaks, and "
                "`split_dataset` refuses a dataset that leaves fewer than 8 training, 2 validation or 2 test records, naming "
                "the split (at least 12 records with one question per page). Under BYOD the printed provenance and "
                "`result.json` describe your file, not the CORD-v2 corpus.\n\n"
                "Look for: 100 + 100 raw rows, three digests, splits 595 / 152 / 229 questions over 119 / 30 / 50 receipts, "
                "the BYOD minimum the code computes, the field mix of the test split, and four refusal probes — a duplicate "
                "id, a gold span outside the words, a box outside the page and a dataset too small to use — each rejected "
                "before `torch` does anything.\n\n"
                "**Predict before running:** the test split has 229 questions over ten field types. Which field do you expect "
                "to have the fewest test questions, and how many questions would you want before trusting a per-field score?"
            ),
            "code": (
                "import collections\n"
                "import hashlib\n"
                "import json\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_path = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_path.is_file():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} is not a file in this runtime: fix the path, or leave BYOD_PATH empty to upload a .json or .jsonl file in Colab.')\n"
                "        file_name = byod_path.name\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the .json or .jsonl file in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one .json or .jsonl file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a file already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_path = Path('work') / Path(file_name).name\n"
                "        byod_path.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_path.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_path)\n"
                "    print({{'byod_records': len(records), 'needed': f'at least {{byod_record_limits()[0]}} records with one question per page', 'split_minimums': split_minimums()}})\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records)}}\n"
                "    byod = {{'file': file_name, 'records': len(records), 'sha256': hashlib.sha256(byod_path.read_bytes()).hexdigest()}}\n"
                "else:\n"
                "    corpus_rows = fetch_corpus(cache_dir='weights/cord-v2')\n"
                "    raw_rows = {{name: len(rows) for name, rows in corpus_rows.items()}}\n"
                "    splits = build_sample_dataset(read_corpus(corpus_rows), seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}} {{CORPUS_RELEASE}} ({{CORPUS_LICENSE}})'\n"
                "minimums = split_minimums()\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=minimums[name]) for name, part in splits.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "pages = {{name: len({{r['page_id'] for r in part}}) for name, part in splits.items()}}\n"
                "fields = {{name: dict(collections.Counter(r.get('field', 'byod') for r in part)) for name, part in splits.items()}}\n"
                "write_dataset_jsonl(splits['train'], 'outputs/{stem}_train.jsonl')\n"
                "print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'pages': pages, 'split_unit': 'page (receipt); no shop or vendor field', 'column_sha256': None if USE_BYOD else {{name: spec['column_sha256'][:16] + '...' for name, spec in CORPUS_FILES.items()}}}})\n"
                "print({{'byod_minimum_records': byod_record_limits()[0], 'split_minimums': minimums}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'unique_pages': manifest['unique_pages'], 'words_per_page': manifest['words_per_page'], 'answer_words': manifest['answer_words'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "print({{'fields_test': fields['test']}})\n"
                "example = splits['train'][0]\n"
                "print({{'example': {{'id': example['id'], 'page_id': example['page_id'], 'question': example['question'], 'answers': example['answers'], 'span': [example['answer_start'], example['answer_end']], 'words': ' '.join(example['words'][:18]) + ' ...'}}}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in splits['train'][:8]],\n"
                "    'gold span outside the words': [{{**splits['train'][0], 'answer_end': len(splits['train'][0]['words'])}}, *splits['train'][1:8]],\n"
                "    'box outside the page': [{{**splits['train'][0], 'boxes': [[0, 0, splits['train'][0]['image_size'][0] + 1, 5], *splits['train'][0]['boxes'][1:]]}}, *splits['train'][1:8]],\n"
                "    'too small': splits['train'][:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes and page counts, `split_unit`, the BYOD minimum (12), the field mix "
                "of the test split, and four rejected probes.\n\n"
                "<details><summary>Check your reasoning</summary>The service-charge field: in the recorded Kaggle Tesla T4 "
                "run the 229 test questions were 50 first item, 46 total, 35 cash, 29 change, 27 subtotal, 17 tax, 12 item "
                "count, 7 credit card, 4 discount and **2 service charge**. A score on 2 or 4 questions moves by 0.25 or 0.5 "
                "when a single answer changes, so it cannot be read as a property of the model; treat any field with fewer "
                "than about 10 questions as anecdote (Section 8 marks them). The BYOD minimum the code prints, 12, is the "
                "smallest one-question-per-page dataset whose seeded 65 / 15 / 20 % split leaves 8 training, 2 validation "
                "and 2 test records.</details>\n\n"
                "## 5. Fit check, then answer through the inference contract\n\n"
                "The window ceiling needs the real tokenizer, so it is applied now that the model is loaded: `pipe.check_fit` "
                "partitions each split into the records whose question and page fit one 512-token window and the ones that "
                "would be **windowed at inference and are therefore not trained on** — nothing is truncated. The dropped ids "
                "are printed and the fitting records are what every later cell uses (the recorded run dropped none of the 976 "
                "sample records; receipts are short).\n\n"
                "Then the inference contract is exercised as the inference-only tutorial exercised it: an invoice-style form is "
                "rendered in code with Pillow's bundled font and the renderer records the pixel box of **every word it draws** "
                "— perfect OCR by construction, a different document family from the receipts, and a page the model will be "
                "asked to read again after adaptation. `validate_inputs` applies exactly the checks `answer` applies (page "
                "size, 1..`MAX_WORDS` non-empty words with one box each inside the page, questions up to `MAX_QUESTION_CHARS`) "
                "and returns an input manifest; a box outside the page is validated too and its rejection recorded as a "
                "finding. `answer` returns the word span, its inclusive `start`/`end` indices (so the answer's boxes are "
                "known), `score`, `n_words`, `n_windows` and the model identity. **Score semantics:** the `score` is the "
                "**product of the start and end softmax probabilities of the chosen span within its window** — a ranking "
                "signal over spans of this page, **not a calibrated probability** that the answer is right, and never a "
                "signal that the question is answerable (Section 10 shows this). Whether the answers are *right* is what "
                "Section 6 measures on 229 gold spans, not what five authored pairs can tell you.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, Section 6 "
                "or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it first reloads the "
                "pretrained model from the verified snapshot with `reset_to_pretrained()`, so a *frozen* number is never read "
                "from the adapted model and a new adapter is never trained on top of the old one.\n\n"
                "**Predict before running:** will the pretrained model answer all five invoice questions exactly? Roughly what "
                "`score` do you expect on a correct answer — near 0.5, or near 1.0?"
            ),
            "code": (
                "import gc\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import Image, ImageDraw, ImageFont\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = LayoutLMDocumentQAPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n\n"
                "reset_to_pretrained()\n"
                "fit = {{name: pipe.check_fit(part) for name, part in splits.items()}}\n"
                "train_records, val_records, test_records = fit['train']['fitting'], fit['validation']['fitting'], fit['test']['fitting']\n"
                "print({{'fit_check': {{name: {{'fitting': f['n_fitting'], 'dropped': f['dropped']}} for name, f in fit.items()}}}})\n"
                "ceilings = {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MAX_WORDS': MAX_WORDS, 'MAX_QUESTION_CHARS': MAX_QUESTION_CHARS, 'MAX_SEQ_LEN': MAX_SEQ_LEN, 'DOC_STRIDE': DOC_STRIDE, 'MAX_ANSWER_TOKENS': MAX_ANSWER_TOKENS, 'BOX_GRID': BOX_GRID, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS}}\n"
                "print(ceilings)\n\n\n"
                "def synthetic_form(width=850, height=1100):\n"
                "    \"\"\"Invoice-style form rendered with Pillow's bundled font; every drawn word is recorded with its pixel box.\"\"\"\n"
                "    page = Image.new('RGB', (width, height), 'white')\n"
                "    d = ImageDraw.Draw(page)\n"
                "    body, bold, head = ImageFont.load_default(size=18), ImageFont.load_default(size=20), ImageFont.load_default(size=30)\n"
                "    words, boxes = [], []\n\n"
                "    def put(x, y, text, font, fill='black'):\n"
                "        for token in text.split():\n"
                "            x0, y0, x1, y1 = d.textbbox((x, y), token, font=font)\n"
                "            d.text((x, y), token, fill=fill, font=font)\n"
                "            words.append(token)\n"
                "            boxes.append([float(x0), float(y0), float(x1), float(y1)])\n"
                "            x = x1 + d.textlength(' ', font=font)\n\n"
                "    put(70, 60, 'INVOICE', head)\n"
                "    put(70, 110, 'Northwind Traders Ltd.', bold)\n"
                "    put(70, 136, '14 Harbour Road, Portsmouth PO1 3AX', body, (40, 40, 40))\n"
                "    y = 200\n"
                "    for label, value in [('Invoice number:', 'NW-2026-0417'), ('Invoice date:', '12 March 2026'), ('Due date:', '11 April 2026'), ('Customer:', 'Blue Yonder Airlines'), ('Purchase order:', 'PO-88213')]:\n"
                "        put(70, y, label, bold)\n"
                "        put(300, y, value, body)\n"
                "        y += 32\n"
                "    d.rectangle([70, 400, 780, 640], outline='black', width=2)\n"
                "    cols = [70, 420, 540, 660, 780]\n"
                "    rows = [('Description', 'Qty', 'Unit price', 'Amount'), ('Cargo pallets (standard)', '40', '$18.50', '$740.00'), ('Shrink wrap rolls', '12', '$9.25', '$111.00'), ('Handling fee', '1', '$65.00', '$65.00')]\n"
                "    for r, row in enumerate(rows):\n"
                "        yy = 400 + r * 48\n"
                "        if r:\n"
                "            d.line([(70, yy), (780, yy)], fill=(120, 120, 120), width=1)\n"
                "        for c, cell in enumerate(row):\n"
                "            put(cols[c] + 10, yy + 14, cell, bold if r == 0 else body)\n"
                "    for c in cols[1:-1]:\n"
                "        d.line([(c, 400), (c, 640)], fill=(120, 120, 120), width=1)\n"
                "    put(540, 670, 'Subtotal:', bold)\n"
                "    put(680, 670, '$916.00', body)\n"
                "    put(540, 700, 'VAT (20%):', bold)\n"
                "    put(680, 700, '$183.20', body)\n"
                "    put(540, 736, 'Total due:', head)\n"
                "    put(680, 736, '$1,099.20', head)\n"
                "    put(70, 900, 'Payment terms: 30 days from invoice date. Bank: Solent Mutual, sort code 40-11-22.', body, (40, 40, 40))\n"
                "    qa = [\n"
                "        ('What is the invoice number?', ['NW-2026-0417']),\n"
                "        ('Who is the customer?', ['Blue Yonder Airlines']),\n"
                "        ('What is the total due?', ['$1,099.20', '1,099.20']),\n"
                "        ('What is the due date?', ['11 April 2026']),\n"
                "        ('How many cargo pallets were invoiced?', ['40']),\n"
                "    ]\n"
                "    return page, words, boxes, qa\n\n\n"
                "image, words, boxes, qa = synthetic_form()\n"
                "questions, golds = [q for q, _ in qa], [g for _, g in qa]\n"
                "image_name = 'synthetic_invoice_850x1100.png'\n"
                "image_sha256 = hashlib.sha256(np.asarray(image.convert('RGB')).tobytes()).hexdigest()\n"
                "input_manifest = validate_inputs(words, boxes, questions, image_size=image.size, names=[image_name])\n"
                "try:\n"
                "    validate_inputs(words[:1], [[0, 0, image.width + 1, 10]], questions, image_size=image.size)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'box-outside-page-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'page': image_name, 'size': image.size, 'rgb_sha256': image_sha256[:16] + '...', 'n_words': len(words), 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n"
                "results = []\n"
                "for question in questions:\n"
                "    started = time.perf_counter()\n"
                "    result = pipe.answer(question, words=words, boxes=boxes, image_size=image.size)\n"
                "    results.append({{'seconds': round(time.perf_counter() - started, 3), **result}})\n"
                "    print(f\"Q: {{result['question']}}\\n   A: {{result['answer']!r}}  score {{result['score']:.4f}}  words {{result['start']}}..{{result['end']}}  windows {{result['n_windows']}}\")\n"
                "checks = {{\n"
                "    'one_result_per_question': len(results) == len(questions),\n"
                "    'span_is_the_indexed_words': all(r['answer'] == ' '.join(words[r['start'] : r['end'] + 1]) for r in results if r['start'] is not None),\n"
                "    'indices_inside_the_page': all(0 <= r['start'] <= r['end'] < r['n_words'] for r in results if r['start'] is not None),\n"
                "    'scores_in_unit_interval': all(0.0 <= r['score'] <= 1.0 for r in results),\n"
                "    'one_window': all(r['n_windows'] == 1 for r in results),\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'answer output failed a sanity check: {{checks}}')\n"
                "frozen_form = evaluation_report(results, golds, sample_kind='synthetic')\n"
                "print({{'checks': checks, 'frozen_invoice': {{m['id']: round(m['value'], 3) for m in frozen_form['metrics']}}, 'verdict': frozen_form['verdict']}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the fit-check line (nothing dropped), the five answers with their word indices and "
                "scores, the five `checks`, and the invoice ANLS with its `sample-sanity` verdict.\n\n"
                "<details><summary>Check your reasoning</summary>Yes, all five, with scores near 1.0. In the recorded T4 run "
                "the pretrained model answered `NW-2026-0417`, `Blue Yonder Airlines`, `$1,099.20`, `11 April 2026` and `40` "
                "with scores 1.0000, 1.0000, 0.9998, 1.0000 and 0.9994 (invoice ANLS 1.0). A clean, perfectly OCR'd form with "
                "labelled fields is the easy case the model was trained for. The scores say the model put almost all its "
                "start and end mass on one span of *this* page; they would be just as high for a wrong span it was sure "
                "of.</details>\n\n"
                "## 6. Baselines and the frozen model's score on the test receipts\n\n"
                "Three numbers frame the adaptation. The **last-number baseline** answers every question with the last word "
                "on the page that contains a digit — receipts end with their totals, so it is right more often than chance "
                "and wrong for everything else. The **keyword-lookup baseline** finds the page word sharing the longest prefix "
                "with a content word of the question (`TOTAL` for *What is the total amount?*) and answers with the next "
                "numeric word after it — the find-the-label-then-read-the-value heuristic a person applies, with no model. "
                "The **frozen model** answers the 229 test questions and is scored with the same two metrics: mean **ANLS** "
                "(DocVQA's normalised Levenshtein similarity, 0 below 0.5) and the **exact-match** rate, both after "
                "lower-casing, punctuation removal and whitespace collapsing. The per-field breakdown prints `n` beside each "
                "field and marks the fields with fewer than 10 questions. The cell records whether the frozen model beats "
                "each baseline; it does not stop when it does not, because on your own data that can be the honest result.\n\n"
                "**Predict before running:** will the frozen model land closer to the keyword-lookup baseline or well above "
                "it? Which field do you expect it to read worst — a total, an item name, or the number of items bought?"
            ),
            "code": (
                "reset_to_pretrained()\n"
                "baseline_last = last_number_baseline(test_records)\n"
                "baseline_lookup = keyword_lookup_baseline(test_records)\n"
                "print({{'last_number_baseline': {{'anls': round(baseline_last['anls'], 3), 'exact_match': round(baseline_last['exact_match'], 3), 'n': baseline_last['n']}}}})\n"
                "print({{'keyword_lookup_baseline': {{'anls': round(baseline_lookup['anls'], 3), 'exact_match': round(baseline_lookup['exact_match'], 3), 'n': baseline_lookup['n']}}}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records)\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': {{'anls': round(frozen_test['anls'], 3), 'exact_match': round(frozen_test['exact_match'], 3), 'n': frozen_test['n'], 'adapted': frozen_test['adapted'], 'verdict': frozen_test['verdict']}}, 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'definitions': frozen_test['definitions']}})\n"
                "SMALL_FIELD = 10  # a per-field score on fewer questions than this is anecdote, not evidence\n\n\n"
                "def by_field(pipeline, records):\n"
                "    \"\"\"Per-field ANLS with its question count, plus every answer (so Section 8 can show where the models differ).\"\"\"\n"
                "    scores, answers = collections.defaultdict(list), {{}}\n"
                "    for record in records:\n"
                "        item = pipeline.answer(record['question'], words=record['words'], boxes=record['boxes'], image_size=record['image_size'])\n"
                "        answers[record['id']] = item['answer']\n"
                "        scores[record.get('field', 'byod')].append(anls(item['answer'], gold_texts(record)))\n"
                "    table = {{field: {{'n': len(values), 'anls': round(sum(values) / len(values), 2), 'too_few_to_read': len(values) < SMALL_FIELD}} for field, values in sorted(scores.items())}}\n"
                "    return table, answers\n\n\n"
                "frozen_fields, frozen_answers = by_field(pipe, test_records)\n"
                "print({{'frozen_by_field': frozen_fields}})\n"
                "frozen_beats_last_number = frozen_test['anls'] > baseline_last['anls']\n"
                "frozen_beats_keyword_lookup = frozen_test['anls'] > baseline_lookup['anls']\n"
                "print({{'frozen_beats_last_number': frozen_beats_last_number, 'frozen_beats_keyword_lookup': frozen_beats_keyword_lookup}})"
            ),
        },
        {
            "md": (
                "**What to notice:** `adapted: False`, the frozen ANLS beside the two baselines, and the per-field rows with "
                "their `n` and `too_few_to_read` flags.\n\n"
                "<details><summary>Check your reasoning</summary>Well above, and the item count. In the recorded T4 run the "
                "last-number baseline scored ANLS 0.406 (exact match 0.253), keyword lookup 0.635 (0.594) and the frozen "
                "model 0.843 (0.782). Per field it read subtotals at 0.98 and totals at 0.91 but item names at 0.79 and "
                "*How many items were bought?* at only **0.17** on 12 questions: the count is a small number printed "
                "somewhere on the receipt with no label the question names, so the DocVQA-trained reader picks a different "
                "number. Those weak fields are where Section 7 has room to move.</details>\n\n"
                "## 7. Bounded fine-tuning of the last encoder blocks and the span head\n\n"
                "`pipe.adapt` trains only the last `TRAINABLE_ENCODER_LAYERS` encoder blocks plus the span head "
                "`qa_outputs` — four blocks by default, 28,353,026 of 127,792,898 parameters; the word, position and 2-D box "
                "embeddings and the earlier blocks stay frozen — with start/end cross-entropy on the first and last token of "
                "the gold word span, AdamW at a fixed learning rate, gradient clipping at 1.0, dynamic padding, seeded "
                "shuffling and no scheduler. Nothing is truncated: every training record passed the fit check. Epoch 0 records "
                "the frozen model's validation ANLS; every epoch is scored on the 152 validation questions, and the epoch with "
                "the highest validation ANLS is kept. The test receipts play no part in this choice. `adapt` refuses a "
                "pipeline that is already adapted, and the cell first reloads the pretrained model if an earlier pass "
                "adapted it.\n\n"
                "**Expected result.** Validation ANLS rises from about **0.82** to about **0.95**: in the recorded Kaggle "
                "Tesla T4 run of the previous notebook version (same model stages; `torch 2.14.0+cu130`, `transformers "
                "4.57.6`, `cuda:0`, Python 3.12.13) it went **0.819 → 0.952** and epoch 5 was kept, in 82 s for six epochs. "
                "**Run-to-run spread.** Training is deterministic for one device and library set but not bit-reproducible "
                "across devices: a CPU pre-flight of the same configuration (`torch 2.14.0`, float32) reached 0.960 at epoch "
                "5 and kept it too, with test ANLS 0.942 against the T4 run's 0.940, and took about two and a half minutes "
                "per epoch. A result within about 0.01 of the quoted one is that spread, not a fault.\n\n"
                "**Predict before running:** will the validation ANLS rise in every epoch? Which epoch do you expect the "
                "selector to keep — always the last one?"
            ),
            "code": (
                "EPOCHS = 6  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 3e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 16  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_ENCODER_LAYERS = 4  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row['val_anls'] = round(entry['val']['anls'], 4)\n"
                "        row['val_exact_match'] = round(entry['val']['exact_match'], 4)\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_encoder_layers=TRAINABLE_ENCODER_LAYERS, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_encoder_layers': adapt_result['trainable_encoder_layers'], 'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'learning_rate': adapt_result['lr'], 'seed': adapt_result['seed'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'selection_split': 'validation', 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, how the training loss and the validation ANLS move "
                "from epoch to epoch, and which epoch is kept.\n\n"
                "<details><summary>Check your reasoning</summary>Almost, and no. In the recorded T4 run the validation ANLS "
                "went 0.819 (epoch 0, the frozen model) → 0.859 → 0.902 → 0.924 → 0.934 → **0.952** → 0.952 while the "
                "training loss fell from 1.37 to 0.38; epoch 6 (0.9518) was a hair below epoch 5 (0.9523), so the selector "
                "kept **epoch 5**. On the CPU pre-flight the curve dipped once (0.908 → 0.894 at epoch 3) and epoch 5 was "
                "kept again. The selector keeps the best validation epoch, not the last one, and never looks at the test "
                "receipts.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test receipts were never used for training or epoch selection, and no test page — by id or by word "
                "content — appears in the training or validation splits. The adapted model is scored exactly as the frozen "
                "model was in Section 6, the four systems are put side by side on both metrics, and the per-field breakdown is "
                "repeated with `n` and the `too_few_to_read` flag. **Read it field by field, not only overall:** a gain can be "
                "concentrated in the fields the frozen model missed, and a field can also **lose** score after adaptation — "
                "in the recorded run one did. A field with only 2 or 4 questions moves by 0.25 or 0.5 when one answer "
                "changes, so its row is anecdote. The cell then prints the test questions where the frozen and the adapted "
                "model **disagree** (up to six), records whether the adapted model beats the frozen one and both baselines, "
                "prints a one-line reading of the outcome and keeps one row per pass in a run history; a result where "
                "adaptation did not help is reported, and the export below still runs. Two hundred and twenty-nine "
                "questions over 50 receipts from one seeded split of one corpus give **no dispersion estimate**; the deltas "
                "are sample-sanity evidence that the adaptation contract works, not a benchmark, and a gain on CORD receipts "
                "with their annotated OCR says nothing about your documents or your OCR until you measure it there.\n\n"
                "**Predict before running:** will every field improve after fine-tuning? Which field do you expect to gain "
                "most, and could one get worse?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records)\n"
                "adapted_val = pipe.evaluate(val_records)\n"
                "adapted_fields, adapted_answers = by_field(pipe, test_records)\n"
                "comparison = {{\n"
                "    'anls': {{'last_number': round(baseline_last['anls'], 3), 'keyword_lookup': round(baseline_lookup['anls'], 3), 'frozen': round(frozen_test['anls'], 3), 'adapted': round(adapted_test['anls'], 3)}},\n"
                "    'exact_match': {{'last_number': round(baseline_last['exact_match'], 3), 'keyword_lookup': round(baseline_lookup['exact_match'], 3), 'frozen': round(frozen_test['exact_match'], 3), 'adapted': round(adapted_test['exact_match'], 3)}},\n"
                "    'delta_vs_frozen': {{'anls': round(adapted_test['anls'] - frozen_test['anls'], 3), 'exact_match': round(adapted_test['exact_match'] - frozen_test['exact_match'], 3)}},\n"
                "    'by_field': {{field: {{'n': frozen_fields[field]['n'], 'frozen': frozen_fields[field]['anls'], 'adapted': adapted_fields[field]['anls'], 'too_few_to_read': frozen_fields[field]['too_few_to_read']}} for field in frozen_fields}},\n"
                "}}\n"
                "for metric, row in comparison.items():\n"
                "    print({{metric: row}})\n"
                "worse_fields = sorted(field for field, row in comparison['by_field'].items() if row['adapted'] < row['frozen'])\n"
                "print({{'fields_that_lost_score': {{field: comparison['by_field'][field] for field in worse_fields}}}})\n"
                "disagreements = [r for r in test_records if frozen_answers[r['id']] != adapted_answers[r['id']]]\n"
                "print({{'questions_where_the_models_disagree': len(disagreements), 'of': len(test_records)}})\n"
                "for record in disagreements[:6]:\n"
                "    print({{'field': record.get('field', 'byod'), 'question': record['question'], 'frozen': frozen_answers[record['id']], 'adapted': adapted_answers[record['id']], 'gold': gold_texts(record)}})\n\n"
                "# Differences below 0.001 (the printed precision) count as no change.\n"
                "adapted_beats_frozen = comparison['delta_vs_frozen']['anls'] > 0\n"
                "adapted_beats_both_baselines = round(adapted_test['anls'] - max(baseline_last['anls'], baseline_lookup['anls']), 3) > 0\n"
                "if adapt_result['best_epoch'] == 0:\n"
                "    reading = 'The selector kept epoch 0, so the adapted model is the frozen model: no epoch beat it on validation.'\n"
                "elif not adapted_beats_frozen:\n"
                "    reading = f\"The adapted ANLS is not above the frozen ANLS on the test receipts (delta {{comparison['delta_vs_frozen']['anls']:+.3f}}): this adaptation did not help here. The export and reload below still run.\"\n"
                "elif worse_fields:\n"
                "    reading = f\"The adapted ANLS is above the frozen ANLS (delta {{comparison['delta_vs_frozen']['anls']:+.3f}}), but not every field gained: {{', '.join(worse_fields)}} lost score (check its n before reading anything into it).\"\n"
                "else:\n"
                "    reading = f\"The adapted ANLS is above the frozen ANLS (delta {{comparison['delta_vs_frozen']['anls']:+.3f}}) and no field lost score.\"\n"
                "outcomes = {{'frozen_beats_last_number': frozen_beats_last_number, 'frozen_beats_keyword_lookup': frozen_beats_keyword_lookup, 'adapted_beats_frozen': adapted_beats_frozen, 'adapted_beats_both_baselines': adapted_beats_both_baselines, 'fields_that_lost_score': worse_fields, 'best_epoch': adapt_result['best_epoch']}}\n"
                "print(outcomes)\n"
                "print('Reading: ' + reading)\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'blocks': TRAINABLE_ENCODER_LAYERS, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'best_epoch': adapt_result['best_epoch'], 'frozen_anls': round(frozen_test['anls'], 3), 'adapted_anls': round(adapted_test['anls'], 3), 'adapted_exact_match': round(adapted_test['exact_match'], 3)}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'blocks':>6}} {{'epochs':>6}} {{'lr':>8}} {{'best':>4}} {{'frozen':>7}} {{'ANLS':>7}} {{'EM':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['blocks']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['best_epoch']:>4}} {{h['frozen_anls']:>7.3f}} {{h['adapted_anls']:>7.3f}} {{h['adapted_exact_match']:>7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'byod': byod,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'pages': pages,\n"
                "    'split_unit': 'page (receipt); no shop or vendor field',\n"
                "    'fit_check': {{name: {{'fitting': f['n_fitting'], 'dropped': f['dropped']}} for name, f in fit.items()}},\n"
                "    'baselines': {{'last_number': baseline_last, 'keyword_lookup': baseline_lookup}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'disagreements': [{{'id': r['id'], 'frozen': frozen_answers[r['id']], 'adapted': adapted_answers[r['id']], 'gold': gold_texts(r)}} for r in disagreements],\n"
                "    'outcomes': outcomes,\n"
                "    'reading': reading,\n"
                "    'run_history': run_history,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta row, the per-field rows with their `n`, `fields_that_lost_score`, the "
                "disagreement examples, the printed reading and the run history.\n\n"
                "<details><summary>Check your reasoning</summary>No, not every field. In the recorded T4 run test ANLS rose "
                "0.843 → 0.940 and exact match 0.782 → 0.921, past both baselines (0.406 and 0.635). The gain was "
                "concentrated where the frozen model had been weak: item count 0.17 → 0.83 (n = 12), first item 0.79 → 0.92 "
                "(n = 50), change 0.87 → 1.00 (n = 29). But **the discount field went down, 1.00 → 0.75**: one of its four "
                "test questions was answered correctly before adaptation and wrongly after. That is a real regression on "
                "this split, and four questions are far too few to say whether adaptation hurts discounts in general — the "
                "same holds for the two service-charge questions (1.00 → 1.00). Fine-tuning moves every answer, and an "
                "overall gain can hide a field that got worse.</details>\n\n"
                "## 9. Re-read the invoice, export the adapter and reload it\n\n"
                "The five authored invoice questions from Section 5 are answered again by the adapted model — a page from a "
                "different document family than the receipts it was tuned on, so this is a small look at what the adaptation "
                "did *outside* its corpus (a lost answer here is a finding to record, not a failure) — and scored with the "
                "per-page `evaluation_report`, whose verdict is `sample-sanity` because five authored pairs on one "
                "perfectly-OCR'd page carry no dispersion estimate. The answers are written as CSV and an annotated PNG draws "
                "the adapted answer spans' boxes on the page.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the last four encoder blocks and the span head, about "
                "113 MB — as `adapter.safetensors`, with a `manifest.json` recording the artifact format, the base model id "
                "and revision, the digest of the base `model.safetensors`, the tensor names, the file size and SHA-256, the "
                "training configuration and the epoch history (OUT8). `LayoutLMDocumentQAPipeline.from_artifact` re-verifies "
                "the base snapshot, checks the artifact manifest, its digest and its exact tensor set **before** deserialising, "
                "refuses any tensor that is not an adaptable encoder-block or span-head tensor, and overlays the tensors onto "
                "a freshly loaded base — a new object from files, not the in-memory model (VER2). The cell compares the "
                "answers of the in-memory and the reloaded model on eight test receipts and stops with an explanation if any "
                "differ (VER4). Parity holds because every adaptation starts from the pretrained base (Section 7), so the "
                "adapter carries every tensor that differs from it.\n\n"
                "**Predict before running:** after tuning on Indonesian receipts, will the adapted model still answer the "
                "five English invoice questions exactly?"
            ),
            "code": (
                "import csv\n"
                "import shutil\n\n"
                "adapted_results = [pipe.answer(question, words=words, boxes=boxes, image_size=image.size) for question in questions]\n"
                "adapted_form = evaluation_report(adapted_results, golds, sample_kind='synthetic')\n"
                "for before, after in zip(results, adapted_results, strict=True):\n"
                "    print({{'question': before['question'], 'frozen': before['answer'], 'adapted': after['answer'], 'gold': golds[questions.index(before['question'])]}})\n"
                "print({{'invoice_after_adaptation': {{m['id']: round(m['value'], 3) for m in adapted_form['metrics']}}, 'verdict': adapted_form['verdict'], 'reason': adapted_form['reason'][:80] + '...'}})\n"
                "with open('outputs/{stem}_answers.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['image', 'question', 'frozen_answer', 'adapted_answer', 'adapted_score', 'start', 'end', 'gold'])\n"
                "    for before, after, gold in zip(results, adapted_results, golds, strict=True):\n"
                "        writer.writerow([image_name, after['question'], before['answer'], after['answer'], f\"{{after['score']:.6f}}\", after['start'], after['end'], ' | '.join(gold)])\n"
                "COLOURS = [(200, 30, 30), (0, 140, 0), (40, 90, 220), (200, 120, 0), (130, 0, 160)]\n"
                "annotated = image.convert('RGB').copy()\n"
                "draw = ImageDraw.Draw(annotated)\n"
                "for index, item in enumerate(adapted_results):\n"
                "    if item['start'] is None:\n"
                "        continue\n"
                "    for box in boxes[item['start'] : item['end'] + 1]:\n"
                "        draw.rectangle([box[0] - 2, box[1] - 2, box[2] + 2, box[3] + 2], outline=COLOURS[index % len(COLOURS)], width=2)\n"
                "annotated.save('outputs/{stem}_annotated.png')\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...'}})\n\n"
                "reloaded = LayoutLMDocumentQAPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "before = [pipe.answer(r['question'], words=r['words'], boxes=r['boxes'], image_size=r['image_size'])['answer'] for r in test_records[:8]]\n"
                "after = [reloaded.answer(r['question'], words=r['words'], boxes=r['boxes'], image_size=r['image_size'])['answer'] for r in test_records[:8]]\n"
                "parity = {{'identical_answers': sum(a == b for a, b in zip(before, after, strict=True)), 'of': len(before)}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "if parity['identical_answers'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the evaluated model; re-run from Section 7, or restart the session and choose Run all.')\n"
                "reloaded = None\n\n"
                "weight_entry = next(entry for entry in MANIFEST['files'] if entry['path'] == WEIGHT_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': weight_entry['sha256']}},\n"
                "    'data_source': data_source,\n"
                "    'byod': byod,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'revision': CORPUS_REVISION, 'release': CORPUS_RELEASE, 'license': CORPUS_LICENSE, 'column': CORPUS_COLUMN, 'files': CORPUS_FILES}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'page': {{'name': image_name, 'size': list(image.size), 'rgb_sha256': image_sha256, 'n_words': len(words)}}, 'items': [{{k: r[k] for k in ('question', 'answer', 'start', 'end', 'score', 'n_windows', 'seconds')}} for r in results], 'golds': golds, 'frozen_report': frozen_form, 'adapted_report': adapted_form}},\n"
                "    'comparison': comparison,\n"
                "    'outcomes': outcomes,\n"
                "    'reading': reading,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
        {
            "md": (
                "**What to notice:** the five frozen / adapted / gold rows, the invoice ANLS after adaptation, the artifact's "
                "tensor count and size, and the reload-parity line.\n\n"
                "<details><summary>Check your reasoning</summary>Yes. In the recorded T4 run the adapted model answered all "
                "five invoice questions exactly as before (ANLS 1.0, `sample-sanity`): the four tuned blocks did not erase "
                "what the model reads on a clean English form — one page of evidence, not a measurement. The artifact held "
                "66 tensors, 113,419,976 bytes, and reload parity was 8/8: the exported adapter is the model that was "
                "evaluated.</details>\n\n"
                "## 10. Try it — questions the page cannot answer\n\n"
                "The model has no abstention: `answer` always returns its best span, and `score` only ranks spans *within* "
                "the page. This cell asks three questions the rendered invoice cannot answer — it has no delivery address, no "
                "VAT registration number and no signature — and prints each answer with its score from the pretrained model "
                "(reloaded from the verified snapshot for this comparison) and from the adapted model, beside the score of "
                "one question the page does answer. Edit `UNSUPPORTED_QUESTIONS` and run only this cell to try your own.\n\n"
                "**Predict before running:** will either model return an empty answer for *What is the delivery address?* If "
                "it returns a span, will its score be clearly lower than the scores in Section 5?"
            ),
            "code": (
                "UNSUPPORTED_QUESTIONS = ['What is the delivery address?', 'What is the VAT registration number?', 'Who signed the invoice?']\n\n"
                "frozen_base = LayoutLMDocumentQAPipeline.from_pretrained(weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "probe_rows = []\n"
                "for question in [questions[0], *UNSUPPORTED_QUESTIONS]:\n"
                "    frozen_item = frozen_base.answer(question, words=words, boxes=boxes, image_size=image.size)\n"
                "    adapted_item = pipe.answer(question, words=words, boxes=boxes, image_size=image.size)\n"
                "    probe_rows.append({{'question': question, 'answerable': question == questions[0], 'frozen': frozen_item['answer'], 'frozen_score': round(frozen_item['score'], 4), 'adapted': adapted_item['answer'], 'adapted_score': round(adapted_item['score'], 4)}})\n"
                "    print(probe_rows[-1])\n"
                "frozen_base = None\n"
                "gc.collect()\n"
                "print({{'empty_answers': sum(1 for row in probe_rows if not row['frozen'] or not row['adapted']), 'note': 'the model has no abstention; a span and a score are returned for every question'}})"
            ),
        },
    ],
    "closing": (
        "**What to notice:** whether any answer is empty, which words the unsupported questions were answered with, and "
        "how their scores compare with the answerable question's.\n\n"
        "<details><summary>Check your reasoning</summary>No answer is empty, and the scores do not reliably separate the "
        "cases: the model always returns its best span, and the span score only says how concentrated its start and end "
        "mass was on this page. In a CPU check of this notebook version the pretrained model answered *What is the "
        "delivery address?* with `14 Harbour Road,` (score 0.2774) — low, but *What is the VAT registration number?* got "
        "`$183.20` (0.9997) and *Who signed the invoice?* got `Northwind Traders Ltd.` (0.9892), as high as the correct "
        "invoice number (1.0000). An unsupported question lands on a plausible-looking span — an address line, a number "
        "near a related label, a name — often with a high score. That is why the notebook never treats `score` as a "
        "confidence and ships no rejection threshold: deciding that a page cannot answer a question needs labelled "
        "unanswerable examples and a calibration you fit yourself.</details>\n\n"
        "## 11. Your turn — change one thing: two trainable blocks\n\n"
        "Optional; **Predict → Change one thing → Run → Observe → Explain**. It retrains, so it takes about as long as "
        "Sections 7–10 did (Section 7 alone took 82 s on the T4 record and about 15 minutes on CPU).\n\n"
        "1. **Predict:** with `TRAINABLE_ENCODER_LAYERS = 2` (half the default), how many tensors will the adapter hold "
        "(the default holds 66), will the test ANLS end above or below the four-block run's, and will the item-count field "
        "still gain? Write your guesses next to the default run's row in the Section 8 run history.\n"
        "2. **Change:** in Section 7 set `TRAINABLE_ENCODER_LAYERS = 2`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained model "
        "before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run history, and "
        "Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation ANLS again (0.819 in the recorded T4 run), not "
        "the adapted one — the sign that the model was reset — and the trainable-parameter count. In Section 8, compare the "
        "two rows of the run history and the per-field rows; in Section 9, the tensor count, the bytes and the reload "
        "parity.\n"
        "5. **Explain:** in one or two sentences, what did training half as many blocks change, and is the difference "
        "between the two runs larger than the run-to-run spread (about 0.01) and than what 229 test questions can "
        "resolve?\n\n"
        "<details><summary>Check your reasoning</summary>Two blocks train 14,177,282 parameters (half the blocks, about "
        "half the trainable weights) and the adapter holds **34 tensors**, about 57 MB. Epoch 0 is 0.819 again and the "
        "reload parity passes, because the run started from the pretrained base. The build record has no run of exactly "
        "this setting; its nearest ones, on an RTX 5070 Ti and the same split, reached test ANLS 0.854 with two blocks "
        "after three epochs at this learning rate and 0.909 after six epochs at `5e-5`, against 0.946 for the default four "
        "blocks there. Expect a lower test ANLS than the four-block run by a few points — more than the run-to-run spread, "
        "so a real effect of depth on this split, but still one split.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The frozen model reads most receipt totals already — its test ANLS (0.843 in the recorded T4 run) sits well above "
        "both non-neural baselines (0.406 and 0.635) — and a bounded fine-tuning of the last four encoder blocks and the "
        "span head on 119 receipts lifts held-out ANLS by several points (to 0.940), concentrated in the fields it had been "
        "missing (item count 0.17 → 0.83, item names 0.79 → 0.92, change 0.87 → 1.00), with a 113 MB adapter that reloads "
        "to identical answers. Not every field gained: the discount field fell from 1.00 to 0.75 — one of its four test "
        "questions lost — which is a real regression on this split and far too few questions to generalise from. That is "
        "the claim: the adaptation contract works end to end on a real gold-span document corpus whose OCR the model never "
        "sees as pixels, and the numbers it produces are read per field against two non-neural baselines and the frozen "
        "model rather than in isolation.\n\n"
        "The test split is 229 questions over 50 receipts from one seeded split of one corpus, the questions are templated from "
        "field categories rather than written by people, the metrics are two reference-based scores (own implementations of "
        "DocVQA's normalisation, neither a human judgement), and the OCR is CORD's annotation — clean words in reading order "
        "with tight boxes, which no OCR engine on a photographed receipt reproduces. The split is by receipt, not by shop, so "
        "the held-out score is an estimate for more receipts of the same kind. So a gain here says the contract works, not "
        "that the adapted model is better on your documents or your OCR, that it handles other languages, handwriting or long "
        "pages, or that its spans are faithful — Section 10 shows a reader returning a span for questions the page cannot "
        "answer, and the adaptation changes nothing about that. Fine-tuning on a narrow corpus can also erode the model "
        "elsewhere; the invoice re-read in Section 9 is one page of evidence about that, not a measurement.\n\n"
        "Three things to carry to real data. **Baselines first:** the last-number and keyword-lookup baselines and the frozen "
        "model's score on *your* gold spans, with *your* OCR, are the numbers to read before any adapted one, per field, with "
        "the number of questions beside each. **Leakage:** keep every question on a page in one split (the contract does "
        "this) and split by document or by vendor when your pages come from few sources, never at random over near-duplicate "
        "pages — CORD-v2 itself contains one duplicated receipt, which the sample drops. **Ceilings:** a question + page over "
        "one 512-token window is answered window by window at inference and dropped from training by the fit check; "
        "long-document training is out of scope.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify one column of a real "
        "annotated corpus, validate the demonstrated dataset contract with no page in two splits, execute the inference "
        "contract and a bounded fine-tuning, evaluate against two trivial baselines and the frozen model on a page-disjoint "
        "split, and emit the shown machine-readable artifacts — without the repository being reachable. It does **not** "
        "establish benchmark superiority, document-understanding accuracy on any other domain or OCR, a usable rejection "
        "threshold, or production fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one thing; note the numbers you "
        "want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before they use it, so no "
        "experiment inherits an earlier adaptation.\n\n"
        "- **Two trainable blocks:** Section 11.\n"
        "- **More epochs:** set `EPOCHS = 8` in Section 7, select Section 7 and choose **Run after**. Epoch 0 is the frozen "
        "0.819 again; does the validation ANLS keep rising after epoch 6, and which epoch does the selector keep?\n"
        "- **A higher learning rate:** set `LEARNING_RATE = 5e-5` in Section 7, select Section 7 and choose **Run after**. The "
        "build record measured 0.936 test ANLS for four blocks at this rate against 0.946 at the default on another GPU: is "
        "your difference larger than the run-to-run spread?\n"
        "- **Your own question:** edit `UNSUPPORTED_QUESTIONS` in Section 10 and run only that cell. Which wrong spans come "
        "back with the highest scores?\n"
        "- **Another split:** change `SPLIT_SEED` in Section 4, select Section 4 and choose **Run after**. How far do the "
        "frozen and adapted ANLS move with a different draw of 50 test receipts — more or less than the run-to-run spread?\n"
        "- **Your own pages:** BYOD (Section 4, then **Run after**). Before the adapted number, how do the two baselines and "
        "the frozen model score on your gold spans, field by field?\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **The run is slow.** On CPU the six epochs take about 15 minutes (Prerequisites); a GPU runtime (**Runtime → "
        "Change runtime type**) takes under two minutes for them.\n"
        "- **\"The isolated environment's Python process exited\" or an out-of-memory error.** Usually the runtime ran out "
        "of memory (Sections 9 and 10 briefly hold two copies of the model). Restart the session and choose **Run all**; "
        "in Section 7, `BATCH_SIZE = 8` needs less memory.\n"
        "- **`FileNotFoundError: snapshot file missing` or a `sha256`/`size` `ValueError` in Section 3.** A staged file is "
        "incomplete or altered — delete it from `weights/layoutlm-document-qa/` and run Section 3 again. A column-digest "
        "mismatch in Section 4 is the same for the cache under `weights/cord-v2/`; a download error there means the Hub was "
        "unreachable — run Section 4 again.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split with too few records (at least 12 "
        "records with one question per page), a line of a `.jsonl` file that is not valid JSON (the message names the "
        "line), a record missing a key or breaking a rule (it names the record), a file that is not `.json` or `.jsonl`, or "
        "a duplicate id. Fix the file and run Section 4 with **Run after** again. An empty or cancelled upload, or a runtime "
        "without the Colab upload dialog, asks you to choose a file or set `BYOD_PATH`.\n"
        "- **Section 8 reads \"did not help\" or \"The selector kept epoch 0\".** Not an error: under these settings the "
        "adaptation did not beat the frozen model. Read the epoch history in Section 7; the export and reload in Section 9 "
        "still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ from the worked answers.** The frozen numbers are the same on CPU and GPU to the printed "
        "precision; training results vary by about 0.01 between devices (Section 7, **Run-to-run spread**). Larger "
        "differences on the default settings mean a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **Extractive question answering:** answering by pointing at a span of the given text (here, a run of OCR words) "
        "rather than generating new text.\n"
        "- **OCR words and boxes:** the words an OCR engine (or here, an annotation) found on the page, each with its pixel "
        "box; the model reads the boxes scaled to a 0–1000 grid.\n"
        "- **Window:** one 512-token slice of question + page; a longer page is read in overlapping windows.\n"
        "- **Span score:** the product of the start and end softmax probabilities of the chosen span within its window — a "
        "ranking signal, not a probability that the answer is right.\n"
        "- **ANLS / exact match:** average normalised Levenshtein similarity to the gold answer (0 below 0.5), and the share "
        "of answers equal to the gold after normalisation.\n"
        "- **Last-number / keyword-lookup baseline:** two readers with no model — the last number on the page, and the next "
        "number after the page word that best matches the question.\n"
        "- **Encoder block / span head:** one of the 12 transformer layers, and the final layer that turns each token into a "
        "start and an end logit; fine-tuning here trains the last blocks and the head only.\n"
        "- **Epoch / validation selection:** one pass over the training questions; the epoch kept is the one with the "
        "highest validation ANLS (epoch 0 = the frozen model).\n"
        "- **Training / validation / test split:** questions used to train, to choose the epoch, and to report the final "
        "result once; split by page, so no page is in two splits.\n"
        "- **Fit check:** the step that drops (never truncates) a training question whose page needs more than one window.\n"
        "- **safetensors / adapter / reload parity:** a tensor file format that cannot run code when loaded; the saved "
        "trained tensors; and the check that a pipeline rebuilt from them and the pinned base gives the same answers.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- The task: from ___ to ___. On the test receipts the last-number baseline scored ANLS ___, keyword lookup ___, the "
        "pretrained model ___ and the adapted model ___ (kept epoch ___).\n"
        "- The field that gained most was ___ (n = ___); a field that lost score was ___ (n = ___), which I can / cannot "
        "read because ___.\n"
        "- For a question the page cannot answer, the model returned ___ with score ___, which shows ___.\n"
        "- Training two blocks instead of four (Section 11) changed ___; the difference is / is not larger than the "
        "run-to-run spread, because ___.\n"
        "- Before trusting this adaptation on my own documents I would measure ___ on ___, with my own OCR, split by ___, "
        "with the baselines first.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/layoutlm-document-qa-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/layoutlm-document-qa-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/layoutlm-document-qa-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model (Impira, MIT): https://huggingface.co/{MODEL_ID}\n"
        "- Upstream architecture code (LayoutLM, Microsoft): https://github.com/microsoft/unilm/tree/master/layoutlm\n"
        "- LayoutLM: Pre-training of Text and Layout for Document Image Understanding (Xu et al., 2019): https://arxiv.org/abs/1912.13318\n"
        "- DocVQA: A Dataset for VQA on Document Images (Mathew, Karatzas, Jawahar, 2020): https://arxiv.org/abs/2007.00398\n"
        "- Scene Text Visual Question Answering — the ANLS metric (Biten et al., 2019): https://arxiv.org/abs/1905.13648\n"
        "- CORD: A Consolidated Receipt Dataset for Post-OCR Parsing (Park et al., NeurIPS 2019 Document Intelligence Workshop; CORD-v2, CC BY 4.0): https://huggingface.co/datasets/naver-clova-ix/cord-v2\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
